-- Minetest 0.4 mod: external_legacy
-- See README.txt for licensing and other information.

-- Aliases to support moreores' ores
minetest.register_alias("moreores:mineral_gold", "default:stone_with_gold")
minetest.register_alias("moreores:gold_block", "default:goldblock")
minetest.register_alias("moreores:gold_lump", "default:gold_lump")
minetest.register_alias("moreores:gold_ingot", "default:gold_ingot")
minetest.register_alias("moreores:mineral_copper", "default:stone_with_copper")
minetest.register_alias("moreores:copper_lump", "default:copper_lump")
minetest.register_alias("moreores:copper_ingot", "default:copper_ingot")
minetest.register_alias("moreores:copper_block", "default:copperblock")
minetest.register_alias("moreores:bronze_ingot", "default:bronze_ingot")
minetest.register_alias("moreores:bronze_block", "default:bronzeblock")

-- Aliases for the diamonds mod by InfinityProject
minetest.register_alias("diamonds:diamond_in_ground", "default:stone_with_diamond")
minetest.register_alias("diamonds:block", "default:diamondblock")
minetest.register_alias("diamonds:sword", "default:sword_diamond")
minetest.register_alias("diamonds:pick", "default:pick_diamond")
minetest.register_alias("diamonds:shovel", "default:shovel_diamond")
minetest.register_alias("diamonds:axe", "default:axe_diamond")
minetest.register_alias("diamonds:diamond", "default:diamond")
minetest.register_alias("diamonds:ingot", "default:diamond")

-- Aliases for the farming mod by PilzAdam
minetest.register_alias("farming:soil", "default:soil")
minetest.register_alias("farming:soil_wet", "default:soil_wet")
minetest.register_alias("farming:wheat_1", "default:wheat_1")
minetest.register_alias("farming:wheat_2", "default:wheat_2")
minetest.register_alias("farming:wheat_3", "default:wheat_3")
minetest.register_alias("farming:wheat_4", "default:wheat_4")
minetest.register_alias("farming:wheat_5", "default:wheat_5")
minetest.register_alias("farming:wheat_6", "default:wheat_6")
minetest.register_alias("farming:wheat_7", "default:wheat_7")
minetest.register_alias("farming:wheat_8", "default:wheat_8")
minetest.register_alias("farming:cotton_1", "default:cotton_1")
minetest.register_alias("farming:cotton_2", "default:cotton_2")
minetest.register_alias("farming:cotton_3", "default:cotton_3")
minetest.register_alias("farming:cotton_4", "default:cotton_4")
minetest.register_alias("farming:cotton_5", "default:cotton_5")
minetest.register_alias("farming:cotton_6", "default:cotton_6")
minetest.register_alias("farming:cotton_7", "default:cotton_7")
minetest.register_alias("farming:cotton_8", "default:cotton_8")
minetest.register_alias("farming:seed_wheat", "default:seed_wheat")
minetest.register_alias("farming:wheat", "default:wheat")
minetest.register_alias("farming:flour", "default:flour")
minetest.register_alias("farming:bread", "default:bread")
minetest.register_alias("farming:seed_cotton", "default:seed_cotton")
minetest.register_alias("farming:string", "default:string")
minetest.register_alias("farming:hoe_wood", "default:hoe_wood")
minetest.register_alias("farming:hoe_stone", "default:hoe_stone")
minetest.register_alias("farming:hoe_steel", "default:hoe_steel")
minetest.register_alias("farming:hoe_bronze", "default:hoe_bronze")
minetest.register_alias("farming:hoe_mese", "default:hoe_mese")
minetest.register_alias("farming:hoe_diamond", "default:hoe_diamond")
